### ISSUE TITLE
ISS4 Crear sección servicios

### ISSUE THREAD

**Issue by kacamargo** [kacamargo/semana-2-56#4]
Se deberá dividir el ancho del sitio en 3 partes y en cada parte se deberá incluir un servicio. Cada servicio debe contar con una breve descripción, un logo, ícono o imagen que lo identifique y un enlace al detalle de los servicios. El elemento donde están los servicios debe de tener un id=”services”.

**Comment by adospinag** [comment]
Tarea finalizada.
